FROM node:18-alpine

WORKDIR /app

# 1. Copiamos las dependencias
COPY package*.json ./
RUN npm install --omit=dev

# 2. Copiamos el código compilado (el main.js que vimos en tu dist)
COPY apps/report-service/dist/main.js .

# 3. Exponemos el puerto TCP definido en main.ts (3012)
EXPOSE 3012

CMD ["node", "main.js"]